Broadcasting

In [2]:
import numpy as np
a = np.array([0,1,2])
b = np.array([5,5,5])

In [3]:
a+b

array([5, 6, 7])

In [4]:
# broadcasting allows these kind of element by element basis operations to be performed on arrays of different size

In [5]:
a+5

array([5, 6, 7])

In [6]:
M=np.ones((3,3))

In [7]:
M

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [8]:
a

array([0, 1, 2])

In [9]:
M+a

array([[ 1.,  2.,  3.],
       [ 1.,  2.,  3.],
       [ 1.,  2.,  3.]])

In [10]:
# scalar
# vector = list of scalars
# matrix = list of vectors

In [16]:
M = np.ones((2,3))
M

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [17]:
a = np.arange(3)
a

array([0, 1, 2])

In [13]:
M.shape

(2, 3)

In [14]:
a.shape

(3,)

In [15]:
# rule 1 in the list
# a is the smallest and will end up having dimensions (1,3)
# rule 2:
# a is streched to (2,3)
# now they can be added

In [18]:
# the rule can bring down
# you cannot add a matrix (2,3) and matrix (3,2)
# it will pass rule 1, but fails rule2 because none of them has 1 as dimensions

In [ ]:
# important

In [19]:
M=np.ones((1,3))
M

array([[ 1.,  1.,  1.]])

In [20]:
a_3=np.array([1,1,1])
a_3

array([1, 1, 1])

In [21]:
a_3[0]

1

In [22]:
M[0]

array([ 1.,  1.,  1.])