week 4, day 1 (monday 7 August 2017):       NUMPY

In [ ]:
# exercise

In [32]:
def compute_reciprocals(values):
    '''Takes a list of floats values and returns a list with reciprocals of the numb
    in the list and puts the value NaN when the value it is reciprocating is 0'''
    list_rec=[]
    for i in values:
        if i==0:
            list_rec.append('Nan')
        else:
            list_rec.append(1/i)
    # example: [4,0,1] returns [0.25, 'Nan',1]
    #print(list_rec)

In [33]:
compute_reciprocals([4,0,1])

In [34]:
# Now do the exercise above using Numpy
import numpy as np

In [35]:
def numpy_compute_recip(values):
    output=np.empty(len(values))
    for i in range(len(values)):
        if values[i]==0:
            output[i]='NaN'
        else:
            output[i]=1.0/values[i]
    #print(output)

In [36]:
my_values = np.random.randint(1,10,size=5)
my_values

array([5, 6, 3, 6, 7])

In [37]:
numpy_compute_recip(my_values)

In [38]:
big_array=np.random.randint(1,100,size=1000000)

In [39]:
# make it a list
big_array_list=list(big_array)

In [40]:
# we want to time them
%timeit numpy_compute_recip(big_array)

1 loop, best of 3: 3.61 s per loop


In [41]:
%timeit compute_reciprocals(big_array_list)

1 loop, best of 3: 403 ms per loop


In [42]:
# when comparing same task with list or numpy
# numpy is much slower then computing with list above

In [43]:
# so why do we use numpy?

---

Vectorised operation or universal function

In [46]:
print(1.0/big_array)

[ 0.03571429  0.01162791  0.02173913 ...,  0.01052632  0.02380952
  0.02439024]


In [47]:
%timeit 1.0/big_array

100 loops, best of 3: 5.16 ms per loop


In [48]:
# our timeit results in class
# numpy speed (sec): 0.85, 0.661, 0.370, 3.61
# list: 0.545, 0.419, 0.495, 0.403
# ufunct: 0.008, 0.006, 0.005, 0.005

In [50]:
5.0/big_array
# it knows to apply it to each term of the array

array([ 0.17857143,  0.05813953,  0.10869565, ...,  0.05263158,
        0.11904762,  0.12195122])

In [52]:
2.7**big_array
# e to the power of numb in big_array

array([  1.19725152e+12,   1.25107607e+37,   6.96198609e+19, ...,
         9.54020254e+40,   1.31002051e+18,   4.85192781e+17])

In [53]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
b = np.arange(1,11)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
a/b

array([ 0.        ,  0.5       ,  0.66666667,  0.75      ,  0.8       ,
        0.83333333,  0.85714286,  0.875     ,  0.88888889,  0.9       ])

In [57]:
np.arange(5)/np.arange(1,6)

array([ 0.        ,  0.5       ,  0.66666667,  0.75      ,  0.8       ])

In [58]:
x = np.arange(9).reshape(3,3)

In [59]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [60]:
2**x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [61]:
x+2*x

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [62]:
np.ufunc?

In [65]:
# very often you have a function that you want to apply to all matrix
y = np.arange(9).reshape(3,3)
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [66]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [68]:
z = x+2*x+x**y
z
# 0 + 2*0 + 0squared by 0
# 1 + 2*1 + 1 squared 2

array([[       1,        4,       10],
       [      36,      268,     3140],
       [   46674,   823564, 16777240]])

In [69]:
# sometimes you see ufunct defined as follows
np.add(x,2)
# for every entry of x add 2

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [70]:
x+2

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [72]:
# other ufunct:
# np.subtract, np.negative, np.multiply, np.divide, np.floor_divide, np.power, np.mod
# np.sin, np.cos, np.power, np.exp, np.logs

In [73]:
# universal functions are numpy equivalent of 'vectorised opertions' in matlab and R
# These are operations that are executed on each cell of matrix/vector
# Universal functions exploit numpy's optimised array to execute in a much quicker way than the
# equivalent list/raw numpy way.