# Boolean Masks

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4,5])

In [3]:
x < 3

array([ True,  True, False, False, False], dtype=bool)

In [4]:
# the x < 3 is applied to elem by elem in the array

In [5]:
x ==3

array([False, False,  True, False, False], dtype=bool)

In [6]:
x != 3

array([ True,  True, False,  True,  True], dtype=bool)

In [10]:
(2*x) == (x**2)
# to know for which element the element multiplied by 2 is equal to its square

array([False,  True, False, False, False], dtype=bool)

In [8]:
# quicker than write complex functions
# much more readable

In [11]:
# to know how many True elements (0 in Python is false, non zero means True)
np.count_nonzero(x<3)

2

In [13]:
np.sum(x<3)
# counting in x<3 how many Trues =1 and false=0

2

In [14]:
rng = np.random.RandomState(0)
x= rng.randint(10, size=(3,4))

In [15]:
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [16]:
np.all(x<8, axis=1)

array([ True, False,  True], dtype=bool)

In [17]:
# set to True if all numbers in the row are less then 8 and do it for each row

In [19]:
np.all(x<6, axis=0)
# ...if all numbers in the column are less then 6 and do it for each column

array([False, False, False, False], dtype=bool)

In [20]:
# example

In [21]:
# generally for ex we want to know all the numbers which are less then 5
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [22]:
x[x<5]
# MASK: you index on a condition rather than a position.
# give me back all the number that satisfy condition x<5
# i am not writing here the index, but the condition

array([0, 3, 3, 3, 2, 4])

In [23]:
# to see where they are however i have to do
x<5

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]], dtype=bool)